import { CalendarEvent } from '../types';

const calendarEvents: Record<string, CalendarEvent[]> = {
  '550e8400-e29b-41d4-a716-446655440000': [
    {
      id: '1',
      title: 'Submit environmental report',
      type: 'deadline',
      date: '2025-04-15',
      status: 'upcoming',
      priority: 'high',
      time: '17:00',
      assignedTo: ['John Smith', 'Sarah Johnson'],
      description: 'Final submission of Q1 environmental impact report',
      location: 'Online',
      duration: '2 hours',
      relatedDocuments: ['env-report-2024-q1.pdf'],
      tags: ['environmental', 'reporting', 'compliance'],
      createdAt: '2025-04-01T10:00:00Z',
      updatedAt: '2025-04-01T10:00:00Z'
    },
    {
      id: '2',
      title: 'Foundation inspection',
      type: 'milestone',
      date: '2025-04-18',
      status: 'upcoming',
      priority: 'high',
      time: '10:00',
      assignedTo: ['Michael Chen', 'Lisa Rodriguez'],
      description: 'Final inspection of building foundation before proceeding with construction',
      location: 'Site A',
      duration: '4 hours',
      relatedDocuments: ['foundation-specs.pdf', 'inspection-checklist.pdf'],
      tags: ['inspection', 'foundation', 'quality'],
      createdAt: '2025-03-28T14:30:00Z',
      updatedAt: '2025-03-28T14:30:00Z'
    },
    {
      id: '3',
      title: 'Team progress meeting',
      type: 'meeting',
      date: '2025-04-20',
      status: 'upcoming',
      priority: 'medium',
      time: '14:00',
      assignedTo: ['David Wilson', 'Emma Thompson', 'Alex Kim'],
      description: 'Weekly team sync to discuss project progress and upcoming tasks',
      location: 'Conference Room B',
      duration: '1 hour',
      relatedDocuments: ['weekly-report.pdf'],
      tags: ['meeting', 'progress', 'team'],
      createdAt: '2025-04-01T09:00:00Z',
      updatedAt: '2025-04-01T09:00:00Z'
    },
    {
      id: '4',
      title: 'Electrical plan review',
      type: 'task',
      date: '2025-04-21',
      status: 'upcoming',
      priority: 'medium',
      time: '11:00',
      assignedTo: ['Robert Brown'],
      description: 'Review and approve updated electrical system plans',
      location: 'Office',
      duration: '3 hours',
      relatedDocuments: ['electrical-plans-v2.pdf'],
      tags: ['electrical', 'review', 'planning'],
      createdAt: '2025-03-29T16:00:00Z',
      updatedAt: '2025-03-29T16:00:00Z'
    },
    {
      id: '5',
      title: 'Site safety audit',
      type: 'task',
      date: '2025-04-22',
      status: 'completed',
      priority: 'high',
      time: '09:00',
      assignedTo: ['Sarah Johnson', 'James Wilson'],
      description: 'Comprehensive safety inspection of all work areas',
      location: 'Construction Site',
      duration: '5 hours',
      relatedDocuments: ['safety-checklist.pdf'],
      tags: ['safety', 'inspection', 'compliance'],
      createdAt: '2025-03-27T13:00:00Z',
      updatedAt: '2025-04-22T17:00:00Z'
    },
    {
      id: '6',
      title: 'Order materials',
      type: 'task',
      date: '2025-04-25',
      status: 'upcoming',
      priority: 'high',
      time: '15:00',
      assignedTo: ['Michael Chen'],
      description: 'Place orders for next phase construction materials',
      location: 'Office',
      duration: '2 hours',
      relatedDocuments: ['materials-list.pdf', 'supplier-quotes.pdf'],
      tags: ['materials', 'procurement', 'planning'],
      createdAt: '2025-04-01T11:00:00Z',
      updatedAt: '2025-04-01T11:00:00Z'
    },
    {
      id: '7',
      title: 'Client walkthrough',
      type: 'meeting',
      date: '2025-04-26',
      status: 'upcoming',
      priority: 'high',
      time: '13:00',
      assignedTo: ['David Wilson', 'Emma Thompson'],
      description: 'Client site visit to review progress and discuss upcoming phases',
      location: 'Site A',
      duration: '2 hours',
      relatedDocuments: ['progress-report.pdf'],
      tags: ['client', 'meeting', 'review'],
      createdAt: '2025-03-28T10:00:00Z',
      updatedAt: '2025-03-28T10:00:00Z'
    },
    {
      id: '8',
      title: 'Demolition completed',
      type: 'milestone',
      date: '2025-04-27',
      status: 'completed',
      priority: 'high',
      time: '16:00',
      assignedTo: ['John Smith'],
      description: 'Final inspection of completed demolition work',
      location: 'Site B',
      duration: '1 hour',
      relatedDocuments: ['demolition-report.pdf'],
      tags: ['demolition', 'milestone', 'inspection'],
      createdAt: '2025-03-26T09:00:00Z',
      updatedAt: '2025-04-27T17:00:00Z'
    },
    {
      id: '9',
      title: 'Phase 1 completion deadline',
      type: 'deadline',
      date: '2025-04-28',
      status: 'upcoming',
      priority: 'high',
      time: '17:00',
      assignedTo: ['David Wilson', 'Sarah Johnson', 'Michael Chen'],
      description: 'Final deadline for completing all Phase 1 activities',
      location: 'Office',
      duration: '1 hour',
      relatedDocuments: ['phase1-checklist.pdf', 'completion-report.pdf'],
      tags: ['deadline', 'phase1', 'completion'],
      createdAt: '2025-03-25T14:00:00Z',
      updatedAt: '2025-03-25T14:00:00Z'
    },
    {
      id: '10',
      title: 'Structural steel installation',
      type: 'milestone',
      date: '2025-05-15',
      status: 'upcoming',
      priority: 'high',
      time: '08:00',
      assignedTo: ['Michael Chen', 'Lisa Rodriguez'],
      description: 'Begin installation of structural steel framework',
      location: 'Site A',
      duration: '8 hours',
      relatedDocuments: ['steel-specs.pdf', 'installation-plan.pdf'],
      tags: ['construction', 'steel', 'milestone'],
      createdAt: '2025-04-01T09:00:00Z',
      updatedAt: '2025-04-01T09:00:00Z'
    },
    {
      id: '11',
      title: 'Monthly safety training',
      type: 'meeting',
      date: '2025-05-20',
      status: 'upcoming',
      priority: 'medium',
      time: '10:00',
      assignedTo: ['All Team Members'],
      description: 'Monthly safety training and certification renewal',
      location: 'Training Room',
      duration: '4 hours',
      relatedDocuments: ['safety-training.pdf'],
      tags: ['safety', 'training', 'compliance'],
      createdAt: '2025-04-15T14:00:00Z',
      updatedAt: '2025-04-15T14:00:00Z'
    },
    {
      id: '12',
      title: 'Building permit renewal',
      type: 'deadline',
      date: '2025-06-01',
      status: 'upcoming',
      priority: 'high',
      time: '16:00',
      assignedTo: ['John Smith'],
      description: 'Submit building permit renewal application',
      location: 'City Hall',
      duration: '2 hours',
      relatedDocuments: ['permit-renewal.pdf'],
      tags: ['permits', 'compliance', 'deadline'],
      createdAt: '2025-04-10T11:00:00Z',
      updatedAt: '2025-04-10T11:00:00Z'
    },
    {
      id: '13',
      title: 'Concrete pour',
      type: 'milestone',
      date: '2025-06-15',
      status: 'upcoming',
      priority: 'high',
      time: '06:00',
      assignedTo: ['Michael Chen', 'David Wilson'],
      description: 'Major concrete pour for foundation slab',
      location: 'Site A',
      duration: '12 hours',
      relatedDocuments: ['concrete-specs.pdf', 'pour-plan.pdf'],
      tags: ['concrete', 'foundation', 'milestone'],
      createdAt: '2025-04-20T09:00:00Z',
      updatedAt: '2025-04-20T09:00:00Z'
    },
    {
      id: '14',
      title: 'Quarterly progress review',
      type: 'meeting',
      date: '2025-06-30',
      status: 'upcoming',
      priority: 'high',
      time: '14:00',
      assignedTo: ['All Stakeholders'],
      description: 'Q2 2025 project progress review with stakeholders',
      location: 'Conference Room A',
      duration: '3 hours',
      relatedDocuments: ['q2-report.pdf'],
      tags: ['review', 'stakeholders', 'quarterly'],
      createdAt: '2025-04-25T15:00:00Z',
      updatedAt: '2025-04-25T15:00:00Z'
    },
    {
      id: '15',
      title: 'Phase 2 completion',
      type: 'milestone',
      date: '2025-07-15',
      status: 'upcoming',
      priority: 'high',
      time: '17:00',
      assignedTo: ['David Wilson', 'Sarah Johnson'],
      description: 'Completion of Phase 2 construction activities',
      location: 'Site A',
      duration: '4 hours',
      relatedDocuments: ['phase2-completion.pdf'],
      tags: ['phase2', 'completion', 'milestone'],
      createdAt: '2025-05-01T10:00:00Z',
      updatedAt: '2025-05-01T10:00:00Z'
    },
    {
      id: '16',
      title: 'Final inspection',
      type: 'deadline',
      date: '2025-07-31',
      status: 'upcoming',
      priority: 'high',
      time: '09:00',
      assignedTo: ['John Smith', 'Michael Chen'],
      description: 'Final building inspection before occupancy',
      location: 'Site A',
      duration: '6 hours',
      relatedDocuments: ['inspection-checklist.pdf'],
      tags: ['inspection', 'final', 'deadline'],
      createdAt: '2025-05-15T14:00:00Z',
      updatedAt: '2025-05-15T14:00:00Z'
    }
  ]
};

export { calendarEvents }; 